version: 2
jobs:
  build:
    docker:
      - image: alpine:edge

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apk add imagemagick git harfbuzz-icu go g++ ghostscript rust cargo openssl-dev fontconfig-dev freetype-dev harfbuzz-dev graphite2-dev libpng-dev tectonic make

      - run:
          name: Run Makefile
          command: export PATH=$HOME/.cargo/bin:$PATH; make

      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr

      - run:
          name: Upload release to GitHub
          command: mkdir upload; cp resume.pdf resume-*.png upload; export PATH=$HOME/go/bin:$PATH; ghr "$(date +'%s')" upload
