version: 2
jobs:
  build:
    docker:
      - image: alpine:edge

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apk add git imagemagick go tectonic make; go install github.com/tcnksm/ghr@latest

      - run:
          name: Run Makefile
          command: export PATH=$HOME/go/bin:$PATH; make upload
