version: 2
jobs:
  build:
    docker:
      - image: alpine:latest

    steps:
      - checkout

      - run:
          name: Update package lists
          command: apk update

      - run:
          name: Install dependencies
          command: apk add imagemagick git harfbuzz-icu go g++ ghostscript rust cargo openssl-dev fontconfig-dev freetype-dev harfbuzz-dev graphite2-dev libpng-dev tectonic

      - run:
          name: Make resume
          command: tectonic resume.tex

      - run:
          name: Make resume images
          command: rm /etc/ImageMagick-7/policy.xml; convert -density 300 resume.pdf -colorspace RGB -background white -alpha remove resume.png

      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr

      - run:
          name: Upload release to GitHub
          command: mkdir upload; cp resume.pdf upload; export PATH=$HOME/go/bin:$PATH; ghr "$(date +'%s')" upload
