version: 2
jobs:
  build:
    docker:
      - image: archlinux/base:latest

    steps:
      - checkout

      - run:
          name: Update package lists
          command: pacman -Syu --noconfirm

      - run:
          name: Install dependencies
          command: pacman -S --noconfirm base-devel imagemagick git harfbuzz-icu go ghostscript

      - run:
          name: Install Rust nightly
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install-rust.sh; chmod +x install-rust.sh; ./install-rust.sh -y --default-toolchain nightly; export PATH=$HOME/.cargo/bin:$PATH

      - run:
          name: Install tectonic
          command: export PATH=$HOME/.cargo/bin:$PATH; cargo install tectonic

      - run:
          name: Make resume
          command: export PATH=$HOME/.cargo/bin:$PATH; tectonic resume.tex

      - run:
          name: Make resume images
          command: rm /etc/ImageMagick-7/policy.xml; convert -density 300 resume.pdf -background white -alpha remove resume.png

      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr

      - run:
          name: Upload release to GitHub
          command: mkdir upload; cp resume.pdf resume.png upload; export PATH=$HOME/go/bin:$PATH; ghr "$(date +'%s')" upload
