version: 2
jobs:
  build:
    docker:
      - image: alpine:edge

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apk add git imagemagick go tectonic icu-data-full make; go install github.com/tcnksm/ghr@latest

      - run:
          name: Run Makefile
          command: export PATH=$HOME/go/bin:$PATH; make upload

          # Set GITHUB_TOKEN to a GitHub personal access token in
          # CircleCI -> Project Settings -> Environment Variables
          #
          # The token must have repository access to be able to upload a new
          # release
