version: 2
jobs:
  build:
    docker:
      - image: archlinux/base:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pacman -S --noconfirm tectonic imagemagick

      - run:
          name: Make resume
          command: make

    artifacts:
    paths:
      - resume.pdf
      - resume.png
      - resume-white.png
      - resume.ps
      - resume.dvi
