version: 2
jobs:
  build:
    docker:
      - image: alpine

    steps:
      - checkout

      - run:
          name: Update package lists
          command: apk update

      - run:
          name: Install dependencies
          command: apk add imagemagick git harfbuzz-icu go g++ ghostscript rust cargo openssl-dev fontconfig-dev freetype-dev harfbuzz-dev graphite2-dev libpng-dev make

      - run:
          name: Install tectonic
          command: export PATH=$HOME/.cargo/bin:$PATH; cargo install tectonic

      - run:
          name: Run Makefile
          command: export PATH=$HOME/.cargo/bin:$PATH; rm /etc/ImageMagick-7/policy.xml; make

      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr

      - run:
          name: Upload release to GitHub
          command: mkdir upload; cp resume.pdf resume.png resume-white.png upload; export PATH=$HOME/go/bin:$PATH; ghr "$(date +'%s')" upload
