name: make release
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: edge
      - run: apk add git imagemagick go tectonic make; go install github.com/tcnksm/ghr@latest
        shell: alpine.sh --root {0}
      - run: export PATH=$HOME/go/bin:$PATH; make upload
        shell: alpine.sh {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
