name: make release
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
    - id: alpine-target
      uses: jirutka/setup-alpine@v1
      with:
        branch: edge
    - run: apk add alpine-conf
      shell: alpine.sh --root {0}
    - run: setup-apkcache ${{ steps.alpine-target.outputs.root-path }}/var/apk/cache
      shell: alpine.sh --root {0}
    - id: alpine-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.alpine-target.outputs.root-path }}/var/apk/cache
        key: alpine-edge-apkcache
        restore-keys: alpine-edge-apkcache
    - uses: actions/checkout@v3
    - run: apk add git imagemagick go tectonic make; go install github.com/tcnksm/ghr@latest
      shell: alpine.sh --root {0}
    - run: export PATH=$HOME/go/bin:$PATH; make upload
      shell: alpine.sh --root {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
