name: make release
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
    - id: alpine-target
      uses: jirutka/setup-alpine@v1
      with:
        branch: edge
    - id: alpine-cache
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/work/_temp/gopath
          /home/runner/work/_temp/tectonic
        key: alpine-edge-tectonic-${{ hashFiles('/home/runner/work/_temp/gopath/**/*', '/home/runner/work/_temp/tectonic/**/*') }}
        restore-keys: alpine-edge-tectonic-
    - uses: actions/checkout@v3
    - run: apk add git imagemagick go ghostscript tectonic make; GOPATH=/home/runner/work/_temp/gopath go install github.com/tcnksm/ghr@latest
      shell: alpine.sh --root {0}
    - run: export HOME=/home/runner/work/_temp/tectonic export PATH=/home/runner/work/_temp/gopath/bin:$PATH; make upload
      shell: alpine.sh --root {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: chmod -R 777 /home/runner/work/_temp
      shell: alpine.sh --root {0}
