name: make release
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
    - id: alpine-target
      uses: jirutka/setup-alpine@v1
      with:
        branch: edge
    - id: alpine-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.alpine-target.outputs.root-path }}/gopath
          ${{ steps.alpine-target.outputs.root-path }}/tectonic/.cache/Tectonic
        key: alpine-edge-tectonic
        restore-keys: alpine-edge-tectonic
    - uses: actions/checkout@v3
    - run: apk add git imagemagick go tectonic make; GOPATH=/gopath go install github.com/tcnksm/ghr@latest
      shell: alpine.sh --root {0}
    - run: export HOME=/tectonic export PATH=/gopath/bin:$PATH; make upload
      shell: alpine.sh --root {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: chmod -R 777 /gopath /tectonic
      shell: alpine.sh --root {0}
